version: '3.8'
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - DOMAIN=${DOMAIN}
      - AUDIENCE=${AUDIENCE}
